//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Address) DeepCopyInto(out *Address) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Address.
func (in *Address) DeepCopy() *Address {
	if in == nil {
		return nil
	}
	out := new(Address)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchParty) DeepCopyInto(out *BranchParty) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(Address)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchParty.
func (in *BranchParty) DeepCopy() *BranchParty {
	if in == nil {
		return nil
	}
	out := new(BranchParty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchRegulationConfig) DeepCopyInto(out *BranchRegulationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchRegulationConfig.
func (in *BranchRegulationConfig) DeepCopy() *BranchRegulationConfig {
	if in == nil {
		return nil
	}
	out := new(BranchRegulationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBranch) DeepCopyInto(out *InvoraBranch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBranch.
func (in *InvoraBranch) DeepCopy() *InvoraBranch {
	if in == nil {
		return nil
	}
	out := new(InvoraBranch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBranch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBranchList) DeepCopyInto(out *InvoraBranchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBranch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBranchList.
func (in *InvoraBranchList) DeepCopy() *InvoraBranchList {
	if in == nil {
		return nil
	}
	out := new(InvoraBranchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBranchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBranchSpec) DeepCopyInto(out *InvoraBranchSpec) {
	*out = *in
	out.InstanceRef = in.InstanceRef
	if in.Party != nil {
		in, out := &in.Party, &out.Party
		*out = new(BranchParty)
		(*in).DeepCopyInto(*out)
	}
	if in.RegulationConfig != nil {
		in, out := &in.RegulationConfig, &out.RegulationConfig
		*out = new(BranchRegulationConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBranchSpec.
func (in *InvoraBranchSpec) DeepCopy() *InvoraBranchSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBranchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBranchStatus) DeepCopyInto(out *InvoraBranchStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBranchStatus.
func (in *InvoraBranchStatus) DeepCopy() *InvoraBranchStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBranchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraConnectedBusiness) DeepCopyInto(out *InvoraConnectedBusiness) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraConnectedBusiness.
func (in *InvoraConnectedBusiness) DeepCopy() *InvoraConnectedBusiness {
	if in == nil {
		return nil
	}
	out := new(InvoraConnectedBusiness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraConnectedBusiness) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraConnectedBusinessList) DeepCopyInto(out *InvoraConnectedBusinessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraConnectedBusiness, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraConnectedBusinessList.
func (in *InvoraConnectedBusinessList) DeepCopy() *InvoraConnectedBusinessList {
	if in == nil {
		return nil
	}
	out := new(InvoraConnectedBusinessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraConnectedBusinessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraConnectedBusinessSpec) DeepCopyInto(out *InvoraConnectedBusinessSpec) {
	*out = *in
	out.InstanceRef = in.InstanceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraConnectedBusinessSpec.
func (in *InvoraConnectedBusinessSpec) DeepCopy() *InvoraConnectedBusinessSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraConnectedBusinessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraConnectedBusinessStatus) DeepCopyInto(out *InvoraConnectedBusinessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraConnectedBusinessStatus.
func (in *InvoraConnectedBusinessStatus) DeepCopy() *InvoraConnectedBusinessStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraConnectedBusinessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}
