//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillableMetricFilter) DeepCopyInto(out *BillableMetricFilter) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillableMetricFilter.
func (in *BillableMetricFilter) DeepCopy() *BillableMetricFilter {
	if in == nil {
		return nil
	}
	out := new(BillableMetricFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingResourceStatus) DeepCopyInto(out *BillingResourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingResourceStatus.
func (in *BillingResourceStatus) DeepCopy() *BillingResourceStatus {
	if in == nil {
		return nil
	}
	out := new(BillingResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingAddon) DeepCopyInto(out *InvoraBillingAddon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingAddon.
func (in *InvoraBillingAddon) DeepCopy() *InvoraBillingAddon {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingAddon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingAddonList) DeepCopyInto(out *InvoraBillingAddonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingAddon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingAddonList.
func (in *InvoraBillingAddonList) DeepCopy() *InvoraBillingAddonList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingAddonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingAddonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingAddonSpec) DeepCopyInto(out *InvoraBillingAddonSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	if in.TaxCodes != nil {
		in, out := &in.TaxCodes, &out.TaxCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingAddonSpec.
func (in *InvoraBillingAddonSpec) DeepCopy() *InvoraBillingAddonSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingAddonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingAddonStatus) DeepCopyInto(out *InvoraBillingAddonStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingAddonStatus.
func (in *InvoraBillingAddonStatus) DeepCopy() *InvoraBillingAddonStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingAddonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingAdyenProvider) DeepCopyInto(out *InvoraBillingAdyenProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingAdyenProvider.
func (in *InvoraBillingAdyenProvider) DeepCopy() *InvoraBillingAdyenProvider {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingAdyenProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingAdyenProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingAdyenProviderList) DeepCopyInto(out *InvoraBillingAdyenProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingAdyenProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingAdyenProviderList.
func (in *InvoraBillingAdyenProviderList) DeepCopy() *InvoraBillingAdyenProviderList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingAdyenProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingAdyenProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingAdyenProviderSpec) DeepCopyInto(out *InvoraBillingAdyenProviderSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	out.ApiKeyRef = in.ApiKeyRef
	if in.HmacKeyRef != nil {
		in, out := &in.HmacKeyRef, &out.HmacKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingAdyenProviderSpec.
func (in *InvoraBillingAdyenProviderSpec) DeepCopy() *InvoraBillingAdyenProviderSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingAdyenProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingAdyenProviderStatus) DeepCopyInto(out *InvoraBillingAdyenProviderStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingAdyenProviderStatus.
func (in *InvoraBillingAdyenProviderStatus) DeepCopy() *InvoraBillingAdyenProviderStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingAdyenProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingCoupon) DeepCopyInto(out *InvoraBillingCoupon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingCoupon.
func (in *InvoraBillingCoupon) DeepCopy() *InvoraBillingCoupon {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingCoupon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingCoupon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingCouponList) DeepCopyInto(out *InvoraBillingCouponList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingCoupon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingCouponList.
func (in *InvoraBillingCouponList) DeepCopy() *InvoraBillingCouponList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingCouponList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingCouponList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingCouponSpec) DeepCopyInto(out *InvoraBillingCouponSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	if in.AmountCents != nil {
		in, out := &in.AmountCents, &out.AmountCents
		*out = new(int64)
		**out = **in
	}
	if in.AmountCurrency != nil {
		in, out := &in.AmountCurrency, &out.AmountCurrency
		*out = new(string)
		**out = **in
	}
	if in.PercentageRate != nil {
		in, out := &in.PercentageRate, &out.PercentageRate
		*out = new(string)
		**out = **in
	}
	if in.ExpirationAt != nil {
		in, out := &in.ExpirationAt, &out.ExpirationAt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingCouponSpec.
func (in *InvoraBillingCouponSpec) DeepCopy() *InvoraBillingCouponSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingCouponSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingCouponStatus) DeepCopyInto(out *InvoraBillingCouponStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingCouponStatus.
func (in *InvoraBillingCouponStatus) DeepCopy() *InvoraBillingCouponStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingCouponStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingCustomer) DeepCopyInto(out *InvoraBillingCustomer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingCustomer.
func (in *InvoraBillingCustomer) DeepCopy() *InvoraBillingCustomer {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingCustomer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingCustomer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingCustomerList) DeepCopyInto(out *InvoraBillingCustomerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingCustomer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingCustomerList.
func (in *InvoraBillingCustomerList) DeepCopy() *InvoraBillingCustomerList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingCustomerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingCustomerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingCustomerSpec) DeepCopyInto(out *InvoraBillingCustomerSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	if in.TaxCodes != nil {
		in, out := &in.TaxCodes, &out.TaxCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingCustomerSpec.
func (in *InvoraBillingCustomerSpec) DeepCopy() *InvoraBillingCustomerSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingCustomerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingCustomerStatus) DeepCopyInto(out *InvoraBillingCustomerStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingCustomerStatus.
func (in *InvoraBillingCustomerStatus) DeepCopy() *InvoraBillingCustomerStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingCustomerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingFeature) DeepCopyInto(out *InvoraBillingFeature) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingFeature.
func (in *InvoraBillingFeature) DeepCopy() *InvoraBillingFeature {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingFeature) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingFeatureList) DeepCopyInto(out *InvoraBillingFeatureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingFeature, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingFeatureList.
func (in *InvoraBillingFeatureList) DeepCopy() *InvoraBillingFeatureList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingFeatureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingFeatureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingFeatureSpec) DeepCopyInto(out *InvoraBillingFeatureSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingFeatureSpec.
func (in *InvoraBillingFeatureSpec) DeepCopy() *InvoraBillingFeatureSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingFeatureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingFeatureStatus) DeepCopyInto(out *InvoraBillingFeatureStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingFeatureStatus.
func (in *InvoraBillingFeatureStatus) DeepCopy() *InvoraBillingFeatureStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingFeatureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingGoCardlessProvider) DeepCopyInto(out *InvoraBillingGoCardlessProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingGoCardlessProvider.
func (in *InvoraBillingGoCardlessProvider) DeepCopy() *InvoraBillingGoCardlessProvider {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingGoCardlessProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingGoCardlessProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingGoCardlessProviderList) DeepCopyInto(out *InvoraBillingGoCardlessProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingGoCardlessProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingGoCardlessProviderList.
func (in *InvoraBillingGoCardlessProviderList) DeepCopy() *InvoraBillingGoCardlessProviderList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingGoCardlessProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingGoCardlessProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingGoCardlessProviderSpec) DeepCopyInto(out *InvoraBillingGoCardlessProviderSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	out.AccessTokenRef = in.AccessTokenRef
	if in.WebhookSecretRef != nil {
		in, out := &in.WebhookSecretRef, &out.WebhookSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingGoCardlessProviderSpec.
func (in *InvoraBillingGoCardlessProviderSpec) DeepCopy() *InvoraBillingGoCardlessProviderSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingGoCardlessProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingGoCardlessProviderStatus) DeepCopyInto(out *InvoraBillingGoCardlessProviderStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingGoCardlessProviderStatus.
func (in *InvoraBillingGoCardlessProviderStatus) DeepCopy() *InvoraBillingGoCardlessProviderStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingGoCardlessProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingInstance) DeepCopyInto(out *InvoraBillingInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingInstance.
func (in *InvoraBillingInstance) DeepCopy() *InvoraBillingInstance {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingInstanceList) DeepCopyInto(out *InvoraBillingInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingInstanceList.
func (in *InvoraBillingInstanceList) DeepCopy() *InvoraBillingInstanceList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingInstanceSpec) DeepCopyInto(out *InvoraBillingInstanceSpec) {
	*out = *in
	out.TokenRef = in.TokenRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingInstanceSpec.
func (in *InvoraBillingInstanceSpec) DeepCopy() *InvoraBillingInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingInstanceStatus) DeepCopyInto(out *InvoraBillingInstanceStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
	if in.LastConnectedAt != nil {
		in, out := &in.LastConnectedAt, &out.LastConnectedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingInstanceStatus.
func (in *InvoraBillingInstanceStatus) DeepCopy() *InvoraBillingInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingMetric) DeepCopyInto(out *InvoraBillingMetric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingMetric.
func (in *InvoraBillingMetric) DeepCopy() *InvoraBillingMetric {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingMetric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingMetricList) DeepCopyInto(out *InvoraBillingMetricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingMetricList.
func (in *InvoraBillingMetricList) DeepCopy() *InvoraBillingMetricList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingMetricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingMetricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingMetricSpec) DeepCopyInto(out *InvoraBillingMetricSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]BillableMetricFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingMetricSpec.
func (in *InvoraBillingMetricSpec) DeepCopy() *InvoraBillingMetricSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingMetricStatus) DeepCopyInto(out *InvoraBillingMetricStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingMetricStatus.
func (in *InvoraBillingMetricStatus) DeepCopy() *InvoraBillingMetricStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingMetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingOrganization) DeepCopyInto(out *InvoraBillingOrganization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingOrganization.
func (in *InvoraBillingOrganization) DeepCopy() *InvoraBillingOrganization {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingOrganization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingOrganization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingOrganizationList) DeepCopyInto(out *InvoraBillingOrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingOrganization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingOrganizationList.
func (in *InvoraBillingOrganizationList) DeepCopy() *InvoraBillingOrganizationList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingOrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingOrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingOrganizationSpec) DeepCopyInto(out *InvoraBillingOrganizationSpec) {
	*out = *in
	out.InstanceRef = in.InstanceRef
	in.WriteSecretToRef.DeepCopyInto(&out.WriteSecretToRef)
	if in.ParentOrgRef != nil {
		in, out := &in.ParentOrgRef, &out.ParentOrgRef
		*out = new(ResourceRef)
		**out = **in
	}
	if in.EnableParentDualWrite != nil {
		in, out := &in.EnableParentDualWrite, &out.EnableParentDualWrite
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingOrganizationSpec.
func (in *InvoraBillingOrganizationSpec) DeepCopy() *InvoraBillingOrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingOrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingOrganizationStatus) DeepCopyInto(out *InvoraBillingOrganizationStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
	if in.ParentOrgRef != nil {
		in, out := &in.ParentOrgRef, &out.ParentOrgRef
		*out = new(ResourceRef)
		**out = **in
	}
	if in.ParentCustomerID != nil {
		in, out := &in.ParentCustomerID, &out.ParentCustomerID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingOrganizationStatus.
func (in *InvoraBillingOrganizationStatus) DeepCopy() *InvoraBillingOrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingOrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingPaymentProvider) DeepCopyInto(out *InvoraBillingPaymentProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingPaymentProvider.
func (in *InvoraBillingPaymentProvider) DeepCopy() *InvoraBillingPaymentProvider {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingPaymentProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingPaymentProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingPaymentProviderList) DeepCopyInto(out *InvoraBillingPaymentProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingPaymentProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingPaymentProviderList.
func (in *InvoraBillingPaymentProviderList) DeepCopy() *InvoraBillingPaymentProviderList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingPaymentProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingPaymentProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingPaymentProviderSpec) DeepCopyInto(out *InvoraBillingPaymentProviderSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	out.CredentialsRef = in.CredentialsRef
	if in.WebhookSecretRef != nil {
		in, out := &in.WebhookSecretRef, &out.WebhookSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingPaymentProviderSpec.
func (in *InvoraBillingPaymentProviderSpec) DeepCopy() *InvoraBillingPaymentProviderSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingPaymentProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingPaymentProviderStatus) DeepCopyInto(out *InvoraBillingPaymentProviderStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingPaymentProviderStatus.
func (in *InvoraBillingPaymentProviderStatus) DeepCopy() *InvoraBillingPaymentProviderStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingPaymentProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingPlan) DeepCopyInto(out *InvoraBillingPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingPlan.
func (in *InvoraBillingPlan) DeepCopy() *InvoraBillingPlan {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingPlanList) DeepCopyInto(out *InvoraBillingPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingPlanList.
func (in *InvoraBillingPlanList) DeepCopy() *InvoraBillingPlanList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingPlanSpec) DeepCopyInto(out *InvoraBillingPlanSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	if in.Charges != nil {
		in, out := &in.Charges, &out.Charges
		*out = make([]PlanCharge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaxCodes != nil {
		in, out := &in.TaxCodes, &out.TaxCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingPlanSpec.
func (in *InvoraBillingPlanSpec) DeepCopy() *InvoraBillingPlanSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingPlanStatus) DeepCopyInto(out *InvoraBillingPlanStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingPlanStatus.
func (in *InvoraBillingPlanStatus) DeepCopy() *InvoraBillingPlanStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingStripeProvider) DeepCopyInto(out *InvoraBillingStripeProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingStripeProvider.
func (in *InvoraBillingStripeProvider) DeepCopy() *InvoraBillingStripeProvider {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingStripeProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingStripeProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingStripeProviderList) DeepCopyInto(out *InvoraBillingStripeProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingStripeProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingStripeProviderList.
func (in *InvoraBillingStripeProviderList) DeepCopy() *InvoraBillingStripeProviderList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingStripeProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingStripeProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingStripeProviderSpec) DeepCopyInto(out *InvoraBillingStripeProviderSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	out.SecretKeyRef = in.SecretKeyRef
	if in.WebhookSecretRef != nil {
		in, out := &in.WebhookSecretRef, &out.WebhookSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingStripeProviderSpec.
func (in *InvoraBillingStripeProviderSpec) DeepCopy() *InvoraBillingStripeProviderSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingStripeProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingStripeProviderStatus) DeepCopyInto(out *InvoraBillingStripeProviderStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingStripeProviderStatus.
func (in *InvoraBillingStripeProviderStatus) DeepCopy() *InvoraBillingStripeProviderStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingStripeProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingSubscription) DeepCopyInto(out *InvoraBillingSubscription) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingSubscription.
func (in *InvoraBillingSubscription) DeepCopy() *InvoraBillingSubscription {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingSubscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingSubscription) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingSubscriptionList) DeepCopyInto(out *InvoraBillingSubscriptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingSubscription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingSubscriptionList.
func (in *InvoraBillingSubscriptionList) DeepCopy() *InvoraBillingSubscriptionList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingSubscriptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingSubscriptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingSubscriptionSpec) DeepCopyInto(out *InvoraBillingSubscriptionSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	if in.CustomerRef != nil {
		in, out := &in.CustomerRef, &out.CustomerRef
		*out = new(ResourceRef)
		**out = **in
	}
	if in.PlanRef != nil {
		in, out := &in.PlanRef, &out.PlanRef
		*out = new(ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingSubscriptionSpec.
func (in *InvoraBillingSubscriptionSpec) DeepCopy() *InvoraBillingSubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingSubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingSubscriptionStatus) DeepCopyInto(out *InvoraBillingSubscriptionStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingSubscriptionStatus.
func (in *InvoraBillingSubscriptionStatus) DeepCopy() *InvoraBillingSubscriptionStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingSubscriptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingTapProvider) DeepCopyInto(out *InvoraBillingTapProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingTapProvider.
func (in *InvoraBillingTapProvider) DeepCopy() *InvoraBillingTapProvider {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingTapProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingTapProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingTapProviderList) DeepCopyInto(out *InvoraBillingTapProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingTapProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingTapProviderList.
func (in *InvoraBillingTapProviderList) DeepCopy() *InvoraBillingTapProviderList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingTapProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingTapProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingTapProviderSpec) DeepCopyInto(out *InvoraBillingTapProviderSpec) {
	*out = *in
	out.InvoraBillingOrganizationRef = in.InvoraBillingOrganizationRef
	out.TapApiKeyRef = in.TapApiKeyRef
	if in.TapPublicKeyRef != nil {
		in, out := &in.TapPublicKeyRef, &out.TapPublicKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.TapWebhookSecretRef != nil {
		in, out := &in.TapWebhookSecretRef, &out.TapWebhookSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingTapProviderSpec.
func (in *InvoraBillingTapProviderSpec) DeepCopy() *InvoraBillingTapProviderSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingTapProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingTapProviderStatus) DeepCopyInto(out *InvoraBillingTapProviderStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingTapProviderStatus.
func (in *InvoraBillingTapProviderStatus) DeepCopy() *InvoraBillingTapProviderStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingTapProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingTax) DeepCopyInto(out *InvoraBillingTax) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingTax.
func (in *InvoraBillingTax) DeepCopy() *InvoraBillingTax {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingTax)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingTax) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingTaxList) DeepCopyInto(out *InvoraBillingTaxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingTax, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingTaxList.
func (in *InvoraBillingTaxList) DeepCopy() *InvoraBillingTaxList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingTaxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingTaxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingTaxSpec) DeepCopyInto(out *InvoraBillingTaxSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingTaxSpec.
func (in *InvoraBillingTaxSpec) DeepCopy() *InvoraBillingTaxSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingTaxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingTaxStatus) DeepCopyInto(out *InvoraBillingTaxStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingTaxStatus.
func (in *InvoraBillingTaxStatus) DeepCopy() *InvoraBillingTaxStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingTaxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingWallet) DeepCopyInto(out *InvoraBillingWallet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingWallet.
func (in *InvoraBillingWallet) DeepCopy() *InvoraBillingWallet {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingWallet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingWallet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingWalletList) DeepCopyInto(out *InvoraBillingWalletList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingWallet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingWalletList.
func (in *InvoraBillingWalletList) DeepCopy() *InvoraBillingWalletList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingWalletList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingWalletList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingWalletSpec) DeepCopyInto(out *InvoraBillingWalletSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
	if in.RecurringTopUp != nil {
		in, out := &in.RecurringTopUp, &out.RecurringTopUp
		*out = new(WalletRecurringTopUp)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingWalletSpec.
func (in *InvoraBillingWalletSpec) DeepCopy() *InvoraBillingWalletSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingWalletSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingWalletStatus) DeepCopyInto(out *InvoraBillingWalletStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingWalletStatus.
func (in *InvoraBillingWalletStatus) DeepCopy() *InvoraBillingWalletStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingWalletStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingWebhookEndpoint) DeepCopyInto(out *InvoraBillingWebhookEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingWebhookEndpoint.
func (in *InvoraBillingWebhookEndpoint) DeepCopy() *InvoraBillingWebhookEndpoint {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingWebhookEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingWebhookEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingWebhookEndpointList) DeepCopyInto(out *InvoraBillingWebhookEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InvoraBillingWebhookEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingWebhookEndpointList.
func (in *InvoraBillingWebhookEndpointList) DeepCopy() *InvoraBillingWebhookEndpointList {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingWebhookEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoraBillingWebhookEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingWebhookEndpointSpec) DeepCopyInto(out *InvoraBillingWebhookEndpointSpec) {
	*out = *in
	out.OrganizationRef = in.OrganizationRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingWebhookEndpointSpec.
func (in *InvoraBillingWebhookEndpointSpec) DeepCopy() *InvoraBillingWebhookEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingWebhookEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoraBillingWebhookEndpointStatus) DeepCopyInto(out *InvoraBillingWebhookEndpointStatus) {
	*out = *in
	in.BillingResourceStatus.DeepCopyInto(&out.BillingResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoraBillingWebhookEndpointStatus.
func (in *InvoraBillingWebhookEndpointStatus) DeepCopy() *InvoraBillingWebhookEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(InvoraBillingWebhookEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanCharge) DeepCopyInto(out *PlanCharge) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanCharge.
func (in *PlanCharge) DeepCopy() *PlanCharge {
	if in == nil {
		return nil
	}
	out := new(PlanCharge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WalletRecurringTopUp) DeepCopyInto(out *WalletRecurringTopUp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WalletRecurringTopUp.
func (in *WalletRecurringTopUp) DeepCopy() *WalletRecurringTopUp {
	if in == nil {
		return nil
	}
	out := new(WalletRecurringTopUp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriteSecretToRef) DeepCopyInto(out *WriteSecretToRef) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriteSecretToRef.
func (in *WriteSecretToRef) DeepCopy() *WriteSecretToRef {
	if in == nil {
		return nil
	}
	out := new(WriteSecretToRef)
	in.DeepCopyInto(out)
	return out
}
